version: '3.9'

services:
  db:
    image: postgres:15
    container_name: gpt_food_db_local
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.local  # 🔥 use the correct Dockerfile for local dev
    container_name: gpt_food_web_local
    command: ./docker/entrypoint.sh  # 🔥 updated path
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pg_data:
