version: '3.9'

services:
  db:
    image: postgres:15
    container_name: gpt_food_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod 
    container_name: gpt_food_web
    restart: always
    entrypoint: docker/entrypoint.prod.sh  
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    expose:
      - "8000"  # internal network port (Nginx will proxy)
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: gpt_food_nginx
    restart: always
    ports:
      - "80:80"  # public access
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # 🔥 corrected nginx.conf path
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:
  media_volume:
